---
title: "Assignment (Term Paper)"
subtitle: "Statistical Programming, Summer Term 2025"
format: pdf
date: today
date-format: long
toc: false
toc-depth: 3
number-sections: false
execute: 
  eval: true
  include: true
  echo: true
---

::: {=latex}
\begin{center}
\textbf{Team Members:}
\vspace{1cm}

 Name 1, Student ID 1 \\
 \vspace{0.5cm}
 Name 2, Student ID 2 \\
 \vspace{0.5cm}
 Name 3, Student ID 3 \\
 \vspace{0.5cm}
 Name 4, Student ID 4

\end{center}
:::



\clearpage

# Assignment (Term Paper)

## Section 1

```{python}
# Example Python code

print("Good Luck with your assignment!")

```

Example inline math $E = mc^2$ and display math:

$$
\int_{a}^{b} f(x) \, dx = F(b) - F(a)
$$


\clearpage

## Section 2


\clearpage

## Section 3


\clearpage

## Section 4


\clearpage


# References

...

\clearpage

# Appendix

...

\clearpage

# Critical Reflexion on the Use of ChatGPT / AI Tools

...

\clearpage

# Declaration of Authenticity

> “We/I hereby certify that We/I have independently prepared the foregoing paper without external assistance and have not used any aids other than those indicated in the attached list. All passages taken verbatim or in substance from publications have been marked as such. Furthermore, We/I certify that We/I have not previously submitted this paper in any other examination procedure.”

\vspace{2cm}

**Place, Date, Signature (1)** _______________________________________

\vspace{2cm}

**Place, Date, Signature (2)** _______________________________________

\vspace{2cm}

**Place, Date, Signature (3)** _______________________________________

\vspace{2cm}

**Place, Date, Signature (4)** _______________________________________